# Minimal settings to update dependencies stored in one private registry
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "src/main/typescript"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/"
    # Check the maven registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
