version: '3'
services:
  postgres:
    image: 'postgres:17.2'
    environment:
      - 'POSTGRES_DB=astromark'
      - 'POSTGRES_PASSWORD=astromark'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'