spring:
  application:
      name: astromark
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: astromark
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate.default_schema: astromark
    show-sql: false
    open-in-view: false
    generate-ddl: true