spring:
  application:
    name: astromark
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: astromark
    show-sql: false
    open-in-view: false
    generate-ddl: true
  sendgrid:
    api-key: ${SPRING_MAIL_KEY}
  jwt:
    secret: ${JWT_SECRET}
server:
  error:
    path: /error
    whitelabel:
      enabled: false
    include-binding-errors: never
    include-message: never
    include-stacktrace: never
    include-exception: false
  port: 8443
  ssl:
    key-store: classpath:keystore/astromark.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    keyStoreType: PKCS12
    keyAlias: astromark
    enabled: true
aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  bucket:
    name: ${AWS_BUCKET_NAME}
  endpoint: ${AWS_ENDPOINT}
