name: Run Spring and Vite

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  JAVA_DISTRO: 'corretto'
  JAVA_MAJOR_VERSION: '21'
  NODE_MAJOR_VERSION: '22'

jobs:
  main-ci-cd:
    name: 'Main Pipeline'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Setup :: Checkout'
        uses: 'actions/checkout@v4'


      - name: 'Setup :: Java'
        uses: 'actions/setup-java@v3'
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_MAJOR_VERSION }}
          cache: 'maven'

      - name: 'Setup :: Node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: ${{ env.NODE_MAJOR_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'src/main/typescript/package-lock.json'

      - name: 'Application :: Build'
        run: ./mvnw package -DskipTests