name: Deploy Javadoc to GitHub Pages

on:
  push:
    branches:
      - 'feature/core'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permission for the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and generate Javadoc
        run: |
          mvn clean package javadoc:jar

      - name: Deploy to GitHub Pages
        uses: actions/github-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: target/site/apidocs